# Compiler
CXX = clang++

# Compiler flags
CXXFLAGS = -Wall -Wextra -std=c++17

# Linker flags (if any specific to Clang)
LDFLAGS =

# Source files
SRCS = main.cpp

# Object files
OBJS = $(SRCS:.cpp=.o)

# Executable name
PARTX = partX

# Default PARTX
all: $(PARTX)

# Linking
$(PARTX): $(OBJS)
	$(CXX) $(LDFLAGS) -o $(PARTX) $(OBJS)

# Compilation
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean up
clean:
	rm -f $(OBJS) $(PARTX)

# Phony targets
.PHONY: all clean